import type { ProductDetailSettings } from '@/lib/product-detail-theme'

/** All columns that exist in the product_detail_settings DB table.
 *  Keep in sync with migrations. Unknown keys are stripped before upsert. */
export const VALID_DB_COLUMNS = new Set([
    'tenant_id',
    'page_background_color',
    'page_background_gradient',
    'header_background_color',
    'header_button_background_color',
    'header_button_icon_color',
    'image_background_color',
    'image_placeholder_color',
    'sale_badge_background_color',
    'sale_badge_text_color',
    'product_name_color',
    'product_name_font_size',
    'product_name_font_weight',
    'breadcrumb_color',
    'breadcrumb_active_color',
    'description_color',
    'description_font_size',
    'dietary_tag_background_color',
    'dietary_tag_text_color',
    'dietary_tag_border_color',
    'variation_section_title_color',
    'variation_section_title_font_size',
    'variation_option_background_color',
    'variation_option_text_color',
    'variation_option_border_color',
    'variation_option_selected_background_color',
    'variation_option_selected_text_color',
    'variation_option_selected_border_color',
    'variation_price_modifier_color',
    'variation_required_badge_color',
    'variation_required_text',
    'variation_optional_text',
    'addon_section_title_color',
    'addon_section_title_font_size',
    'addon_background_color',
    'addon_text_color',
    'addon_border_color',
    'addon_selected_background_color',
    'addon_selected_text_color',
    'addon_selected_border_color',
    'addon_selected_check_color',
    'addon_price_color',
    'addon_price_free_text',
    'addon_optional_text',
    'related_section_title_color',
    'related_section_title_font_size',
    'related_item_background_color',
    'related_item_name_color',
    'related_item_price_color',
    'footer_background_color',
    'footer_border_color',
    'footer_shadow_color',
    'summary_text_color',
    'total_price_color',
    'original_price_color',
    'footer_empty_summary_text',
    'quantity_controls_background',
    'quantity_button_color',
    'quantity_text_color',
    'buy_now_button_background',
    'buy_now_button_text_color',
    'buy_now_button_border_color',
    'buy_now_button_label',
    'add_to_cart_button_background',
    'add_to_cart_button_text_color',
    'add_to_cart_button_shadow_color',
    'add_to_cart_button_label',
    'modal_background_color',
    'modal_close_button_color',
    'modal_close_button_background',
    'popup_modal_background_color',
    'popup_modal_title_color',
    'popup_modal_description_color',
    'popup_modal_price_color',
    'popup_modal_button_color',
    'popup_modal_button_text_color',
    'popup_modal_border_color',
    'checkout_modal_background_color',
    'checkout_modal_title_color',
    'checkout_modal_description_color',
    'checkout_modal_price_color',
    'checkout_modal_button_color',
    'checkout_modal_button_text_color',
    'checkout_modal_border_color',
    'font_family_heading',
    'font_family_body',
    'section_padding',
    'card_border_radius',
    'button_border_radius',
    'enable_animations',
    'animation_speed',
])

/** Strip keys that aren't real DB columns + meta fields the DB manages */
export function stripToDBColumns(settings: Partial<ProductDetailSettings>): Record<string, unknown> {
    const result: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(settings)) {
        if (VALID_DB_COLUMNS.has(key) && value !== undefined) {
            result[key] = value
        }
    }
    return result
}
