#!/usr/bin/env node
/**
 * Generate SQL that rewrites old image URLs to the URLs produced by restore.mjs.
 *
 *   node image-backup/relink.mjs
 *
 * Writes image-backup/relink.sql. Review it, then run it in the Supabase SQL
 * editor. Only rows containing an old URL are touched.
 */
import { existsSync, readFileSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const DIR = dirname(fileURLToPath(import.meta.url))
const RESULT = join(DIR, 'restore-result.json')
const OUT = join(DIR, 'relink.sql')

const TEXT_COLUMNS = [
  ['menu_items', 'image_url'],
  ['bundles', 'image_url'],
  ['categories', 'icon'],
  ['addon_library', 'image_url'],
  ['inventory_items', 'image_url'],
  ['outlets', 'image_url'],
  ['tenants', 'logo_url'],
  ['tenants', 'flash_screen_image_url'],
  ['tenants', 'promotion_image_url'],
  ['tenants', 'background_image_url'],
  ['tenants', 'hero_image_url'],
  ['tenants', 'footer_logo_url'],
  ['payment_methods', 'qr_code_url'],
  ['platform_payment_methods', 'qr_code_url'],
  ['orders', 'payment_method_qr_code_url'],
  ['orders', 'payment_proof_url'],
  ['checkout_leads', 'payment_proof_url'],
  ['order_payments', 'proof_url'],
  ['platform_announcements', 'cover_image_url'],
]

const JSONB_COLUMNS = [
  ['menu_items', 'addons'],
  ['menu_items', 'variation_types'],
  ['menu_items', 'variations'],
  ['menu_items', 'modifier_groups'],
  ['categories', 'default_addons'],
  ['tenants', 'promotion_banners'],
  ['tenants', 'welcome_page_banners'],
  ['platform_announcements', 'blocks'],
]

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

async function main() {
  if (!existsSync(RESULT)) {
    console.error('restore-result.json not found — run restore.mjs --go first.')
    process.exit(1)
  }

  const result = JSON.parse(readFileSync(RESULT, 'utf8'))
  const pairs = []
  for (const [oldUrl, r] of Object.entries(result)) {
    if (r.status !== 'ok' || !r.url) continue
    const aliases = [oldUrl, ...(r.aliases || []), r.oldUrl].filter(Boolean)
    for (const from of new Set(aliases)) {
      if (from === r.url) continue
      pairs.push([from, r.url])
    }
  }

  pairs.sort((a, b) => b[0].length - a[0].length)

  const lines = [
    '-- Auto-generated by image-backup/relink.mjs. Review before running.',
    `-- ${pairs.length} URL rewrite(s) from restore-result.json.`,
    'BEGIN;',
    '',
  ]

  for (const [from, to] of pairs) {
    const f = sqlString(from)
    const t = sqlString(to)
    const like = sqlString(`%${from}%`)
    for (const [table, col] of TEXT_COLUMNS) {
      lines.push(`UPDATE ${table} SET ${col} = replace(${col}, ${f}, ${t}) WHERE ${col} LIKE ${like};`)
    }
    for (const [table, col] of JSONB_COLUMNS) {
      lines.push(
        `UPDATE ${table} SET ${col} = replace(${col}::text, ${f}, ${t})::jsonb WHERE ${col}::text LIKE ${like};`,
      )
    }
    lines.push('')
  }

  lines.push('COMMIT;')
  await writeFile(OUT, lines.join('\n'))
  console.log(`Wrote ${OUT} (${pairs.length} rewrite(s))`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
