-- SQL to add menu for tenant: 8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861
-- Generated on: $(date)

-- Insert Categories
INSERT INTO public.categories (tenant_id, name, description, "order", is_active) VALUES
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', 'SILOG', 'MEALS (Rice&Egg)', 1, true),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', 'SIZZLING', 'MEALS (Rice/Creamy Gravy)', 2, true),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', 'ULAM ONLY', '(PANG-PULUTAN)', 3, true),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', 'COMBO MEAL', 'Special combination meals', 4, true),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', 'SNACK', 'Quick snacks and appetizers', 5, true);

-- Get category IDs for reference (these will be generated by the database)
-- We'll use subqueries to get the category IDs

-- Insert SILOG menu items (Price: PHP 95)
INSERT INTO public.menu_items (tenant_id, category_id, name, description, price, image_url, "order", is_available, is_featured) VALUES
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Beef Tapa', 'Tender beef tapa with rice and egg', 95.00, '', 1, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Lechon Kawali', 'Crispy pork belly with rice and egg', 95.00, '', 2, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Sausage', 'Juicy sausage with rice and egg', 95.00, '', 3, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Liempo', 'Grilled pork belly with rice and egg', 95.00, '', 4, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Porkchop', 'Breaded pork chop with rice and egg', 95.00, '', 5, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Chicken', 'Fried chicken with rice and egg', 95.00, '', 6, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Longanisa', 'Sweet Filipino sausage with rice and egg', 95.00, '', 7, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Bangus', 'Milkfish with rice and egg', 95.00, '', 8, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Tocino', 'Sweet cured pork with rice and egg', 95.00, '', 9, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Hotdog', 'Hotdog with rice and egg', 95.00, '', 10, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Shanghai', 'Spring rolls with rice and egg', 95.00, '', 11, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Corned Beef', 'Corned beef with rice and egg', 95.00, '', 12, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SILOG'), 'Skinless', 'Skinless chicken with rice and egg', 95.00, '', 13, true, false);

-- Insert SIZZLING menu items (Price: PHP 95)
INSERT INTO public.menu_items (tenant_id, category_id, name, description, price, image_url, "order", is_available, is_featured) VALUES
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SIZZLING'), 'Pork Sisig', 'Sizzling pork sisig with rice and creamy gravy', 95.00, '', 1, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SIZZLING'), 'Chicken', 'Sizzling chicken with rice and creamy gravy', 95.00, '', 2, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SIZZLING'), 'Sausage', 'Sizzling sausage with rice and creamy gravy', 95.00, '', 3, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SIZZLING'), 'Lechon Kawali', 'Sizzling lechon kawali with rice and creamy gravy', 95.00, '', 4, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SIZZLING'), 'Liempo', 'Sizzling liempo with rice and creamy gravy', 95.00, '', 5, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SIZZLING'), 'Porkchop', 'Sizzling porkchop with rice and creamy gravy', 95.00, '', 6, true, false);

-- Insert ULAM ONLY menu items (Individual pricing)
INSERT INTO public.menu_items (tenant_id, category_id, name, description, price, image_url, "order", is_available, is_featured) VALUES
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'ULAM ONLY'), 'Lechon Kawali', 'Crispy pork belly only', 160.00, '', 1, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'ULAM ONLY'), 'Shanghai ONLY', 'Spring rolls only', 110.00, '', 2, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'ULAM ONLY'), 'Sisig ONLY', 'Pork sisig only', 150.00, '', 3, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'ULAM ONLY'), 'Buttered Hotdog', 'Buttered hotdog only', 150.00, '', 4, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'ULAM ONLY'), 'JUMBO SIOMAI', 'Jumbo siomai only', 120.00, '', 5, true, false);

-- Insert COMBO MEAL menu item
INSERT INTO public.menu_items (tenant_id, category_id, name, description, price, image_url, "order", is_available, is_featured) VALUES
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'COMBO MEAL'), 'COMBO MEAL', '2 ULAM IN ONE MEAL! w/ RICE, EGG & Shanghai', 160.00, '', 1, true, true);

-- Insert SNACK menu items (Price: PHP 50)
INSERT INTO public.menu_items (tenant_id, category_id, name, description, price, image_url, "order", is_available, is_featured) VALUES
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SNACK'), 'SQUIDBALL', 'Fried squid balls', 50.00, '', 1, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SNACK'), 'KIKIAM', 'Fried kikiam', 50.00, '', 2, true, false),
('8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861', (SELECT id FROM public.categories WHERE tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861' AND name = 'SNACK'), 'CHEESY FRIES', 'Crispy fries with cheese', 50.00, '', 3, true, false);

-- Verify the data was inserted correctly
SELECT 
    c.name as category_name,
    c.description as category_description,
    mi.name as menu_item_name,
    mi.description as menu_item_description,
    mi.price
FROM public.categories c
LEFT JOIN public.menu_items mi ON c.id = mi.category_id
WHERE c.tenant_id = '8e1dbc23-ec8b-4e0b-8d6c-1aa72b87c861'
ORDER BY c."order", mi."order";
