#!/usr/bin/env node
/**
 * Relink the database after a restore that changed the Cloudinary cloud name.
 *
 * Only needed when restore.mjs uploaded to a DIFFERENT cloud than the original.
 * Because restore preserves the public_id, the ONLY thing that changes in a URL
 * is the cloud-name segment. So relinking = replacing '/<oldcloud>/' with
 * '/<newcloud>/' across every column that can hold a URL.
 *
 * It derives the old->new cloud mapping from restore-result.json (old URL ->
 * new URL), then generates idempotent SQL UPDATE statements into relink.sql.
 *
 *   node cloudinary-backup/relink-db.mjs        # generate relink.sql + print mapping
 *
 * Review relink.sql, then run it via the Supabase SQL editor / MCP apply.
 * (Generating SQL rather than executing directly keeps this dependency-free and
 * lets you eyeball the exact changes before they touch production data.)
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const DIR = dirname(fileURLToPath(import.meta.url))
const RESULT = join(DIR, 'restore-result.json')
const OUT = join(DIR, 'relink.sql')

// Every (table, column) pair that can contain a Cloudinary URL.
// Plain text columns and jsonb columns are both handled via text replace().
const TEXT_COLUMNS = [
  ['menu_items', 'image_url'],
  ['bundles', 'image_url'],
  ['categories', 'icon'],
  ['tenants', 'logo_url'],
  ['tenants', 'flash_screen_image_url'],
  ['tenants', 'promotion_image_url'],
  ['payment_methods', 'qr_code_url'],
  ['platform_payment_methods', 'qr_code_url'],
  ['orders', 'payment_method_qr_code_url'],
  ['checkout_leads', 'payment_proof_url'],
]
const JSONB_COLUMNS = [
  ['menu_items', 'addons'],
  ['menu_items', 'variation_types'],
  ['menu_items', 'variations'],
  ['categories', 'default_addons'],
  ['tenants', 'promotion_banners'],
]

function cloudOf(url) {
  try { return new URL(url).pathname.split('/').filter(Boolean)[0] } catch { return null }
}

async function main() {
  const map = JSON.parse(await readFile(RESULT, 'utf8'))
  const cloudPairs = new Map() // oldCloud -> newCloud
  for (const [oldUrl, newUrl] of Object.entries(map)) {
    const o = cloudOf(oldUrl), n = cloudOf(newUrl)
    if (o && n && o !== n) cloudPairs.set(o, n)
  }

  if (cloudPairs.size === 0) {
    console.log('No cloud-name changes detected in restore-result.json.')
    console.log('Restore re-used the same cloud(s) → delivery URLs are identical → no DB relink needed.')
    return
  }

  const lines = [
    '-- Auto-generated by relink-db.mjs. Review before running.',
    '-- Replaces old Cloudinary cloud names with the restored cloud names.',
    'BEGIN;',
  ]
  for (const [oldCloud, newCloud] of cloudPairs) {
    const oldSeg = `/${oldCloud}/`, newSeg = `/${newCloud}/`
    lines.push(`\n-- ${oldCloud} -> ${newCloud}`)
    for (const [t, c] of TEXT_COLUMNS) {
      lines.push(`UPDATE ${t} SET ${c} = replace(${c}, '${oldSeg}', '${newSeg}') WHERE ${c} LIKE '%${oldSeg}%';`)
    }
    for (const [t, c] of JSONB_COLUMNS) {
      lines.push(`UPDATE ${t} SET ${c} = replace(${c}::text, '${oldSeg}', '${newSeg}')::jsonb WHERE ${c}::text LIKE '%${oldSeg}%';`)
    }
  }
  lines.push('\nCOMMIT;')
  await writeFile(OUT, lines.join('\n') + '\n')

  console.log('Cloud mapping detected:')
  for (const [o, n] of cloudPairs) console.log(`  ${o}  ->  ${n}`)
  console.log(`\nWrote ${OUT}. Review it, then apply via the Supabase SQL editor / MCP apply_migration.`)
}

main().catch((e) => { console.error(e); process.exit(1) })
