/**
 * Structural CSS shared by every design. `.S` is replaced by the render
 * scope's class. Selectors use two classes so they beat the storefront's
 * global `.storefront-themed h1 { font-family }` heading rule.
 */
export const HERO_BASE_CSS = [
  '.S{container-type:inline-size;container-name:hb;position:relative;width:100%;overflow-x:clip;color:var(--hb-text);font-family:var(--hb-body-font);line-height:1.5;-webkit-font-smoothing:antialiased}',
  '.S *,.S *::before,.S *::after{box-sizing:border-box}',
  '.S .hb-section{position:relative;display:flex;flex-direction:column;isolation:isolate;padding:64px 24px}',
  '.S .hb-row{position:relative;z-index:1;display:flex;flex-direction:row;width:100%;max-width:1200px;margin-inline:auto;gap:32px}',
  '.S .hb-col{position:relative;display:flex;flex-direction:column;gap:16px;min-width:0;flex:var(--hb-w, 1) 1 0%}',
  '.S .hb-w{position:relative;display:block;min-width:0;max-width:100%}',
  '.S .hb-bg-video,.S .hb-bg-overlay{position:absolute;inset:0;z-index:0;pointer-events:none;overflow:hidden}',
  '.S .hb-bg-video{display:none}',
  '.S .hb-bg-video video{width:100%;height:100%;object-fit:cover}',
  '.S .hb-heading,.S .hb-text{margin:0;font:inherit;color:inherit;letter-spacing:inherit;text-transform:inherit;overflow-wrap:break-word}',
  '.S .hb-text a{color:inherit;text-decoration:underline;text-underline-offset:2px}',
  '.S .hb-btns{display:flex;flex-wrap:wrap;gap:12px}',
  '.S .hb-btn{display:inline-flex;align-items:center;justify-content:center;gap:.5em;min-height:44px;padding:.8em 1.6em;border:2px solid transparent;border-radius:var(--hb-btn-radius);font:inherit;font-weight:600;line-height:1.2;text-align:center;text-decoration:none;cursor:pointer;transition:transform .15s ease,filter .15s ease}',
  '.S .hb-btn:hover{filter:brightness(.93);transform:translateY(-1px)}',
  '.S .hb-btn:focus-visible{outline:2px solid var(--hb-btn-bg);outline-offset:3px}',
  '.S .hb-btn--solid{background:var(--hb-btn-bg);color:var(--hb-btn-fg)}',
  '.S .hb-btn--outline{background:transparent;border-color:var(--hb-btn-bg);color:var(--hb-btn-bg)}',
  '.S .hb-btn--ghost{background:transparent;color:var(--hb-btn-bg);padding-inline:.5em}',
  '.S .hb-btn svg{width:1.1em;height:1.1em;flex:none}',
  '.S .hb-w--image{overflow:hidden}',
  '.S .hb-w--image a{display:block}',
  '.S .hb-w--image img{display:block;width:100%;height:auto;object-fit:cover}',
  '.S .hb-media{position:relative;width:100%;aspect-ratio:16 / 9;overflow:hidden;background:#000}',
  '.S .hb-media iframe,.S .hb-media video{position:absolute;inset:0;width:100%;height:100%;border:0;object-fit:cover}',
  '.S .hb-icon-inner{display:inline-flex;align-items:center;justify-content:center;color:inherit;text-decoration:none}',
  '.S .hb-icon-inner svg{width:40px;height:40px}',
  '.S .hb-list{display:flex;flex-direction:column;gap:10px;margin:0;padding:0;list-style:none}',
  '.S .hb-list--inline{flex-direction:row;flex-wrap:wrap;column-gap:24px}',
  '.S .hb-list li{display:flex;align-items:flex-start;gap:.6em}',
  '.S .hb-list svg{flex:none;width:1.25em;height:1.25em;margin-top:.12em;color:var(--hb-accent)}',
  '.S .hb-badge{display:inline-flex;align-items:center;gap:.45em;max-width:100%}',
  '.S .hb-badge svg{width:1.1em;height:1.1em;flex:none}',
  '.S .hb-cd{display:flex;flex-wrap:wrap;gap:12px}',
  '.S .hb-cd-box{display:flex;flex-direction:column;align-items:center;min-width:3.4em;padding:.55em .75em;border-radius:12px;background:var(--hb-cd-bg);color:var(--hb-cd-fg)}',
  '.S .hb-cd-num{font-size:1.9em;font-weight:700;line-height:1;font-variant-numeric:tabular-nums}',
  '.S .hb-cd-label{margin-top:.4em;font-size:.68em;letter-spacing:.08em;text-transform:uppercase;opacity:.8}',
  '.S .hb-divider{width:100%;height:0;margin:0;border:0;border-top:1px solid currentColor;opacity:.9}',
  '.S .hb-divider--dashed{border-top-style:dashed}',
  '.S .hb-divider--dotted{border-top-style:dotted}',
  '.S .hb-gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}',
  '.S .hb-gallery img{display:block;width:100%;aspect-ratio:1 / 1;object-fit:cover}',
  '.S .hb-embed iframe{display:block;width:100%;border:0;background:transparent}',
  // Layout + paint containment: nothing inside an HTML block (even
  // position:fixed) can paint outside its box or over the checkout.
  '.S .hb-html{display:block;contain:layout paint;overflow:hidden}',
  // Welcome page: the "how to order" block. Tile/button colours fall back to
  // the theme when the merchant leaves them blank (set per node in css.ts).
  '.S .hb-entry{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}',
  '.S .hb-entry-opt,.S .hb-entry-cta{appearance:none;margin:0;border:2px solid transparent;font:inherit;line-height:1.25;cursor:pointer;-webkit-tap-highlight-color:transparent;transition:transform .15s ease,filter .15s ease,border-color .15s ease}',
  '.S .hb-entry-opt{display:flex;flex-direction:column;align-items:center;gap:.6em;flex:1 1 0%;min-width:96px;max-width:240px;padding:1.1em .7em;border-radius:var(--hb-entry-radius,18px);background:var(--hb-entry-bg,var(--hb-surface));color:var(--hb-entry-fg,var(--hb-text));border:1px solid color-mix(in srgb,var(--hb-entry-fg,var(--hb-text)) 14%,transparent);text-align:center}',
  '.S .hb-entry-opt:hover{transform:translateY(-1px);border-color:color-mix(in srgb,var(--hb-entry-ic-color,var(--hb-primary)) 45%,transparent)}',
  '.S .hb-entry-opt:focus-visible,.S .hb-entry-cta:focus-visible{outline:2px solid var(--hb-entry-ic-color,var(--hb-primary));outline-offset:3px}',
  '.S .hb-entry-opt:active,.S .hb-entry-cta:active{transform:scale(.98)}',
  '.S .hb-entry-ic{display:inline-flex;flex:none;align-items:center;justify-content:center;width:calc(var(--hb-entry-ic,26px) * 1.9);height:calc(var(--hb-entry-ic,26px) * 1.9);border-radius:999px;background:color-mix(in srgb,var(--hb-entry-ic-color,var(--hb-primary)) 12%,transparent);color:var(--hb-entry-ic-color,var(--hb-primary))}',
  '.S .hb-entry-ic svg{width:var(--hb-entry-ic,26px);height:var(--hb-entry-ic,26px)}',
  '.S .hb-entry-txt{display:flex;flex-direction:column;gap:.15em;min-width:0}',
  '.S .hb-entry-label{font-weight:700}',
  '.S .hb-entry-blurb{font-size:.8em;opacity:.72}',
  '.S .hb-entry-go{flex:none;width:1.1em;height:1.1em;margin-left:auto;opacity:.55}',
  '.S .hb-entry--list{flex-direction:column;flex-wrap:nowrap}',
  '.S .hb-entry--list .hb-entry-opt{flex-direction:row;flex:0 0 auto;width:100%;max-width:none;gap:.9em;padding:.85em 1.1em;text-align:left}',
  '.S .hb-entry-skel{cursor:default;pointer-events:none;animation:hb-entry-pulse 1.2s ease-in-out infinite alternate}',
  '.S .hb-entry-skel>*{visibility:hidden}',
  '.S .hb-entry-cta{display:inline-flex;align-items:center;justify-content:center;gap:.6em;min-height:52px;padding:.95em 2em;border-radius:var(--hb-entry-radius,18px);background:var(--hb-entry-bg,var(--hb-primary));color:var(--hb-entry-fg,var(--brand-button-primary-text,#fff));font-weight:700}',
  '.S .hb-entry-cta:hover{filter:brightness(.94);transform:translateY(-1px)}',
  '.S .hb-entry-cta svg{width:1.15em;height:1.15em;flex:none}',
  '.S .hb-logo{display:flex;justify-content:center}',
  '.S .hb-logo img{display:block;height:var(--hb-logo-h,80px);width:auto;max-width:100%;object-fit:contain}',
  '.S .hb-logo-name{display:block;margin:0;font:inherit;color:inherit;overflow-wrap:break-word}',
  '.S .hb-slides{display:flex;flex-direction:column;gap:10px}',
  '.S .hb-slides-track{display:flex;width:100%;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;border-radius:var(--hb-slide-radius,18px)}',
  '.S .hb-slides-track::-webkit-scrollbar{display:none}',
  '.S .hb-slide{position:relative;flex:0 0 100%;margin:0;aspect-ratio:var(--hb-slide-aspect,16 / 9);scroll-snap-align:center;overflow:hidden}',
  '.S .hb-slide a{display:block;width:100%;height:100%}',
  '.S .hb-slide img{display:block;width:100%;height:100%;object-fit:var(--hb-slide-fit,cover)}',
  '.S .hb-slide figcaption{position:absolute;inset:auto 0 0 0;padding:2.5em 1em .9em;background:linear-gradient(to top,rgba(0,0,0,.7),transparent);color:#fff;text-align:left}',
  '.S .hb-slide-title{display:block;font-weight:700}',
  '.S .hb-slide-caption{display:block;font-size:.85em;opacity:.9}',
  '.S .hb-dots{display:flex;justify-content:center;gap:6px}',
  '.S .hb-dot{appearance:none;width:6px;height:6px;padding:0;border:0;border-radius:999px;background:var(--hb-dot,var(--hb-text));opacity:.25;cursor:pointer;transition:width .2s ease,opacity .2s ease}',
  '.S .hb-dot[aria-current="true"]{width:20px;opacity:.8}',
  '.S .hb-placeholder{display:flex;align-items:center;justify-content:center;min-height:120px;border:1px dashed rgba(100,116,139,.5);border-radius:12px;color:rgba(100,116,139,.9);font-size:13px;background:rgba(148,163,184,.08)}',
  '@keyframes hb-fade{from{opacity:0}to{opacity:1}}',
  '@keyframes hb-entry-pulse{from{opacity:.45}to{opacity:.9}}',
  '@keyframes hb-slide-up{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}',
  '@keyframes hb-slide-down{from{opacity:0;transform:translateY(-28px)}to{opacity:1;transform:none}}',
  '@keyframes hb-slide-left{from{opacity:0;transform:translateX(28px)}to{opacity:1;transform:none}}',
  '@keyframes hb-slide-right{from{opacity:0;transform:translateX(-28px)}to{opacity:1;transform:none}}',
  '@keyframes hb-zoom{from{opacity:0;transform:scale(.92)}to{opacity:1;transform:none}}',
  '@media (prefers-reduced-motion: reduce){.S .hb-w{animation:none!important}.S .hb-btn,.S .hb-entry-opt,.S .hb-entry-cta{transition:none}.S .hb-entry-skel{animation:none}}',
].join('')
