/**
 * Guardrails for the committed Convex push bundle.
 *
 * The Deploy Schema button does not compile anything: it pushes
 * `src/lib/convex-push-bundle.json`, an artifact regenerated by
 * `npm run convex:prebundle` and committed to the repo. So a change to
 * `convex-template/convex/` reaches exactly zero tenants until that artifact is
 * rebuilt — and the failure is silent, because the old bundle pushes cleanly.
 *
 * Two distinct hazards live here, and both have already happened once:
 *
 * - A **stale** bundle. The template gains a module, nobody re-runs the
 *   prebundle, and every tenant keeps running the previous code while the source
 *   tree says otherwise.
 * - A **poisoned** bundle. Unit tests sit beside the modules they cover so the
 *   platform repo's Jest run can reach them (`pushRecipients.test.ts`). If the
 *   bundler stops excluding them, `describe`/`it` — which do not exist in the
 *   Convex runtime — ship to every tenant.
 *
 * Neither is visible from a unit test of the template modules themselves, which
 * is why this asserts on the shipped artifact.
 */
import { readdirSync } from 'fs'
import { join } from 'path'

import bundle from '@/lib/convex-push-bundle.json'

const CONVEX_DIR = join(__dirname, '..', '..', 'convex-template', 'convex')

/** The filenames the bundler recorded as its inputs. */
const shippedSources: string[] = bundle._meta?.sourceFiles ?? []

/** Test files in a list of bundler inputs. Extracted so it can be proven both ways. */
function testModulesIn(sourceFiles: readonly string[]): string[] {
  return sourceFiles.filter((f) => f.endsWith('.test.ts') || f.endsWith('.spec.ts'))
}

/** Every template module the bundler is expected to compile. */
function templateModules(): string[] {
  return readdirSync(CONVEX_DIR)
    .filter((f) => f.endsWith('.ts') && !f.startsWith('_'))
    .filter((f) => testModulesIn([f]).length === 0)
    .sort()
}

describe('committed convex push bundle', () => {
  it('never ships a unit test into the tenant runtime', () => {
    // `describe` and `it` are not defined in the Convex runtime, so a leaked
    // test module breaks the push for every tenant at once.
    expect(testModulesIn(shippedSources)).toEqual([])
  })

  it('is not stale — it carries every template module', () => {
    // The whole point of the artifact is that it is the thing tenants run. A
    // module present in the source tree but absent here is code nobody has.
    expect([...shippedSources].sort()).toEqual(templateModules())
  })

  it('carries the branch-targeting rule, not just a reference to it', () => {
    // `pushRecipients.ts` decides which devices a new order rings. esbuild
    // inlines it into the modules that import it, so the compiled output — not
    // the source list — is what proves it actually shipped.
    expect(JSON.stringify(bundle)).toContain('recipientsForOutlet')
  })
})

describe('the exclusion rule that keeps tests out of the bundle', () => {
  it('has teeth — it rejects a test module', () => {
    // Proves the assertion above can fail. Without this, a bundler that stopped
    // reporting its inputs at all would make the guard silently vacuous.
    expect(testModulesIn(['orders.ts', 'pushRecipients.test.ts'])).toEqual([
      'pushRecipients.test.ts',
    ])
  })

  it('would have caught the filter this bundler shipped before', () => {
    // The original filter was `endsWith(".ts") && !startsWith("_")`, which
    // matched `pushRecipients.test.ts` the moment that file was added.
    const preFixFilter = readdirSync(CONVEX_DIR).filter(
      (f) => f.endsWith('.ts') && !f.startsWith('_')
    )
    expect(testModulesIn(preFixFilter)).not.toEqual([])
  })
})
